CURRENT_ROOM_ADDR = 0x006C
CURRENT_ROOM = nil
EBON_KEEP_FLAG_ADDR = 0x7e22dd  --Useful?
EBON_KEEP_FLAG = false

ROOM_MAPPING =
{

    [0x04] = {"Caves", "Sealed"},            --Sealed Cave 1
    [0x05] = {"Caves", "Sealed"},            --Sealed Cave 2
    [0x06] = {"Caves", "Sealed"},            --Sealed Cave 3
    [0x07] = {"Caves", "Sealed"},            --Sealed Cave 4
    [0x08] = {"Caves", "Sealed"},            --Sealed Cave 5
    [0x09] = {"Caves", "Sealed"},            --Sealed Cave 6
    [0x0a] = {"Caves", "Sealed"},            --Sealed Cave 7
    [0x0c] = {"Caves", "Sealed"},            --Sealed Cave 8
    [0x44] = {"Caves", "Kirisa Plant"},            --Kirisa Plant Cave 1
    [0x45] = {"Caves", "Kirisa Plant"},            --Kirisa Plant Cave 2
    [0x46] = {"Caves", "Kirisa Plant"},            --Kirisa Plant Cave 3
    [0x48] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 1
    [0x49] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 2
    [0x4a] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 3
    [0x4b] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave Dead End
    [0x4c] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 4
    [0x4d] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 5
    [0x4e] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 6
    [0x4f] = {"Caves", "Fog Lamp"},            --Fog Lamp Cave 7
    [0x54] = {"Caves", "Waterfall"},            --Waterfall Cave 1
    [0x55] = {"Caves", "Waterfall"},            --Waterfall Cave 2
    [0x56] = {"Caves", "Waterfall"},            --Waterfall Cave 3
    [0x57] = {"Caves", "Waterfall"},            --Waterfall Cave 4
    [0x6c] = {"Fortresses", "Sabera's"},            --Sabera Palace 1
    [0x6d] = {"Fortresses", "Sabera's"},            --Sabera Palace 2
    [0x6e] = {"Fortresses", "Sabera's"},            --Sabera Palace 3
    [0x88] = {"Fortresses", "Styx"},            --Styx 1
    [0x89] = {"Fortresses", "Styx"},            --Styx 2
    [0x8a] = {"Fortresses", "Styx"},            --Styx 3
    [0x9c] = {"Fortresses", "Pyramid Front"},            --Pyramid - Entrance
    [0x9d] = {"Fortresses", "Pyramid Front"},            --Pyramid - Branch
    [0x9e] = {"Fortresses", "Pyramid Front"},            --Pyramid - Main
    [0x9f] = {"Fortresses", "Pyramid Front"},            --Pyramid - Draygon
    [0xa0] = {"Fortresses", "Pyramid Back"},            --Crypt - Entrance
    [0xa1] = {"Fortresses", "Pyramid Back"},            --Crypt - Hall 1
    [0xa2] = {"Fortresses", "Pyramid Back"},            --Crypt - Branch
    [0xa3] = {"Fortresses", "Pyramid Back"},            --Crypt - Dead End Left
    [0xa4] = {"Fortresses", "Pyramid Back"},            --Crypt - Dead End Right
    [0xa5] = {"Fortresses", "Pyramid Back"},            --Crypt - Hall 2
    [0xa6] = {"Fortresses", "Pyramid Back"},            --Crypt - Draygon Revisited
    [0xa7] = {"Fortresses", "Pyramid Back"},            --Crypt - Teleporter
    [0xa8] = {"Goa", "Kelbesque"},            --Goa Fortress - Entrance
    [0xa9] = {"Goa", "Kelbesque"},            --Goa Fortress - Kelbesque
    [0xaa] = {"Goa", "Kelbesque"},            --Goa Fortress - Zebu
    [0xab] = {"Goa", "Sabera"},            --Goa Fortress - Sabera
    [0xac] = {"Goa", "Sabera"},            --Goa Fortress - Tornel
    [0xad] = {"Goa", "Mado"},            --Goa Fortress - Mado 1
    [0xae] = {"Goa", "Mado"},            --Goa Fortress - Mado 2
    [0xaf] = {"Goa", "Mado"},            --Goa Fortress - Mado 3
    [0xb0] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 1
    [0xb1] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 2
    [0xb2] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 3
    [0xb3] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 4
    [0xb4] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 5
    [0xb5] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 6
    [0xb6] = {"Goa", "Karmine"},            --Goa Fortress - Karmine 7
    [0xb7] = {"Goa", "Karmine"},            --Goa Fortress - Exit
    [0xb9] = {"Goa", "Mado"},            --Goa Fortress - Asina
    [0xba] = {"Goa", "Karmine"},            --Goa Fortress - Kensu
    [0x11] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 1
    [0x20] = {"Mountains", "Sabre West"},            --Mt Sabre West - Lower
    [0x21] = {"Mountains", "Sabre West"},            --Mt Sabre West - Upper
    [0x22] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 2
    [0x23] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 3
    [0x24] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 4
    [0x25] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 5
    [0x26] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 6
    [0x27] = {"Mountains", "Sabre West"},            --Mt Sabre West - Cave 7
    [0x28] = {"Mountains", "Sabre North"},            --Mt Sabre North - Main
    [0x29] = {"Mountains", "Sabre North"},            --Mt Sabre North - Middle
    [0x2a] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 1
    [0x2b] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 2
    [0x2c] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 3
    [0x2d] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 4
    [0x2e] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 5
    [0x2f] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 6
    [0x30] = {"Mountains", "Sabre North"},            --Mt Sabre North - Left Cell
    [0x31] = {"Mountains", "Sabre North"},            --Mt Sabre North - Prison Key Hall
    [0x32] = {"Mountains", "Sabre North"},            --Mt Sabre North - Right Cell
    [0x33] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 7
    [0x34] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 8
    [0x35] = {"Mountains", "Sabre North"},            --Mt Sabre North - Summit Cave
    [0x38] = {"Mountains", "Sabre North"},            --Mt Sabre North - Entrance Cave
    [0x39] = {"Mountains", "Sabre North"},            --Mt Sabre North - Cave 5a
    [0x7c] = {"Mountains", "Mt. Hydra"},            --Mt Hydra
    [0x7d] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 1
    [0x7f] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 2
    [0x80] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 3
    [0x81] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 4
    [0x82] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 5
    [0x83] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 6
    [0x84] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 7
    [0x85] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 8
    [0x86] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 9
    [0x87] = {"Mountains", "Mt. Hydra"},            --Mt Hydra - Cave 10
    [0x00] = {"Overworld"},            --Mezame Shrine
    [0x01] = {"Overworld"},            --Leaf - Outside Start
    [0x02] = {"Overworld"},            --Leaf
    [0x03] = {"Overworld"},            --Valley of Wind
    [0x0e] = {"Overworld"},            --Windmill Cave
    [0x0f] = {"Overworld"},            --Windmill
    [0x10] = {"Overworld"},            --Zebu Cave
    [0x14] = {"Overworld"},            --Cordel Plains West
    [0x15] = {"Overworld"},            --Cordel Plains East
    [0x18] = {"Overworld"},            --Brynmaer
    [0x19] = {"Overworld"},            --Outside Stom House
    [0x1a] = {"Overworld"},            --Swamp
    [0x1b] = {"Overworld"},            --Amazones
    [0x1c] = {"Overworld"},            --Oak
    [0x1e] = {"Overworld"},            --Stom House
    [0x3c] = {"Overworld"},            --Nadare - Inn
    [0x3d] = {"Overworld"},            --Nadare - Tool Shop
    [0x3e] = {"Overworld"},            --Nadare - Back Room
    [0x40] = {"Overworld"},            --Waterfall Valley North
    [0x41] = {"Overworld"},            --Waterfall Valley South
    [0x42] = {"Overworld"},            --Lime Tree Valley
    [0x43] = {"Overworld"},            --Lime Tree Lake
    [0x47] = {"Overworld", "Kirisa Plant"},            --Kirisa Meadow
    [0x50] = {"Overworld"},            --Portoa
    [0x51] = {"Overworld"},            --Portoa - Fisherman Island
    [0x52] = {"Overworld"},            --Mesia Shrine
    [0x58] = {"Overworld"},            --Tower - Entrance
    [0x59] = {"Overworld"},            --Tower 1
    [0x5a] = {"Overworld"},            --Tower 2
    [0x5b] = {"Overworld"},            --Tower 3
    [0x5c] = {"Overworld"},            --Tower - Outside Mesia
    [0x5d] = {"Overworld"},            --Tower - Outside Dyna
    [0x5e] = {"Overworld"},            --Tower - Mesia
    [0x5f] = {"Overworld"},            --Tower - Dyna
    [0x60] = {"Overworld"},            --Angry Sea
    [0x61] = {"Overworld"},            --Cabin
    [0x62] = {"Overworld"},            --Joel - Lighthouse
    [0x64] = {"Overworld"},            --Underground Channel
    [0x65] = {"Overworld"},            --Zombie Town
    [0x68] = {"Overworld", "Evil Spirit Island"},            --Evil Spirit Island 1
    [0x69] = {"Overworld", "Evil Spirit Island"},            --Evil Spirit Island 2
    [0x6a] = {"Overworld", "Evil Spirit Island"},            --Evil Spirit Island 3
    [0x6b] = {"Overworld", "Evil Spirit Island"},            --Evil Spirit Island 4
    [0x70] = {"Overworld"},            --Joel - Secret Passage
    [0x71] = {"Overworld"},            --Joel
    [0x72] = {"Overworld"},            --Swan
    [0x73] = {"Overworld"},            --Swan - Gate
    [0x78] = {"Overworld"},            --Goa Valley
    [0x7e] = {"Overworld"},            --Mt Hydra - Outside Shyron
    [0x8c] = {"Overworld"},            --Shyron
    [0x8e] = {"Overworld"},            --Goa
    [0x8f] = {"Overworld"},            --Goa Fortress - Oasis Entrance
    [0x90] = {"Overworld"},            --Desert 1
    [0x91] = {"Overworld", "Oasis"},            --Oasis Cave - Main
    [0x92] = {"Overworld"},            --Desert Cave 1
    [0x93] = {"Overworld"},            --Sahara
    [0x94] = {"Overworld"},            --Sahara - Outside Cave
    [0x95] = {"Overworld"},            --Desert Cave 2
    [0x96] = {"Overworld"},            --Sahara Meadow
    [0x98] = {"Overworld"},            --Desert 2
    [0xb8] = {"Overworld", "Oasis"},            --Oasis Cave - Entrance
    [0xbb] = {"Overworld"},            --Goa - House
    [0xbc] = {"Overworld"},            --Goa - Inn
    [0xbe] = {"Overworld"},            --Goa - Tool Shop
    [0xbf] = {"Overworld"},            --Goa - Tavern
    [0xc0] = {"Overworld"},            --Leaf - Elder House
    [0xc1] = {"Overworld"},            --Leaf - Rabbit Hut
    [0xc2] = {"Overworld"},            --Leaf - Inn
    [0xc3] = {"Overworld"},            --Leaf - Tool Shop
    [0xc4] = {"Overworld"},            --Leaf - Item Shop
    [0xc5] = {"Overworld"},            --Leaf - Student House
    [0xc6] = {"Overworld"},            --Brynmaer - Tavern
    [0xc7] = {"Overworld"},            --Brynmaer - Pawn Shop
    [0xc8] = {"Overworld"},            --Brynmaer - Inn
    [0xc9] = {"Overworld"},            --Brynmaer - Armor Shop
    [0xcb] = {"Overworld"},            --Brynmaer - Item Shop
    [0xcd] = {"Overworld"},            --Oak - Elder House
    [0xce] = {"Overworld"},            --Oak - Mother House
    [0xcf] = {"Overworld"},            --Oak - Tool Shop
    [0xd0] = {"Overworld"},            --Oak - Inn
    [0xd1] = {"Overworld"},            --Amazones - Inn
    [0xd2] = {"Overworld"},            --Amazones - Item Shop
    [0xd3] = {"Overworld"},            --Amazones - Armor Shop
    [0xd4] = {"Overworld"},            --Amazones - Elder
    [0xd5] = {"Overworld"},            --Nadare
    [0xd6] = {"Overworld"},            --Portoa - Fisherman House
    [0xd7] = {"Overworld"},            --Portoa - Palace Entrance
    [0xd8] = {"Overworld"},            --Portoa - Fortune Teller
    [0xd9] = {"Overworld"},            --Portoa - Pawn Shop
    [0xda] = {"Overworld"},            --Portoa - Armor Shop
    [0xdc] = {"Overworld"},            --Portoa - Inn
    [0xdd] = {"Overworld"},            --Portoa - Tool Shop
    [0xde] = {"Overworld"},            --Portoa - Palace Left
    [0xdf] = {"Overworld"},            --Portoa - Palace Throne Room
    [0xe0] = {"Overworld"},            --Portoa - Palace Right
    [0xe1] = {"Overworld"},            --Portoa - Asina Room
    [0xe2] = {"Overworld"},            --Amazones - Elder Downstairs
    [0xe3] = {"Overworld"},            --Joel - Elder House
    [0xe4] = {"Overworld"},            --Joel - Shed
    [0xe5] = {"Overworld"},            --Joel - Tool Shop
    [0xe7] = {"Overworld"},            --Joel - Inn
    [0xe8] = {"Overworld"},            --Zombie Town - House
    [0xe9] = {"Overworld"},            --Zombie Town - House Basement
    [0xeb] = {"Overworld"},            --Swan - Tool Shop
    [0xec] = {"Overworld"},            --Swan - Stom Hut
    [0xed] = {"Overworld"},            --Swan - Inn
    [0xee] = {"Overworld"},            --Swan - Armor Shop
    [0xef] = {"Overworld"},            --Swan - Tavern
    [0xf0] = {"Overworld"},            --Swan - Pawn Shop
    [0xf1] = {"Overworld"},            --Swan - Dance Hall
    [0xf2] = {"Overworld"},            --Shyron - Temple
    [0xf3] = {"Overworld"},            --Shyron - Training Hall
    [0xf4] = {"Overworld"},            --Shyron - Hospital
    [0xf5] = {"Overworld"},            --Shyron - Armor Shop
    [0xf6] = {"Overworld"},            --Shyron - Tool Shop
    [0xf7] = {"Overworld"},            --Shyron - Inn
    [0xf8] = {"Overworld"},            --Sahara - Inn
    [0xf9] = {"Overworld"},            --Sahara - Tool Shop
    [0xfa] = {"Overworld"},            --Sahara - Elder House
    [0xfb] = {"Overworld"},            --Sahara - Pawn Shop
    

}
